name: "🐛 Сообщить об ошибке (Bug Report)"
description: |
  Используйте этот шаблон, чтобы сообщить о любой ошибке, сбое или неожиданном поведении в игре.
  **Может заполнять любой член команды или тестировщик.**
title: "[BUG] "
labels: ["type: bug", "status: backlog"]
assignees: []  # ИСПРАВЛЕНО: пустой массив вместо пустой строки
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Описание бага
        *Опишите проблему четко и последовательно.*

  - type: input
    id: bug_summary
    attributes:
      label: "Краткое описание"
      description: "Что сломалось? Одним предложением."
      placeholder: "Например: Игра вылетает при попытке съесть частицу пищи."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Шаги для воспроизведения"
      description: "Пошаговая инструкция, как вызвать баг. Будьте точны."
      placeholder: |
        1. Запустите игру из ветки `develop`.
        2. Создайте новую клетку в пруду.
        3. Управляя клеткой, направьтесь к синей частице пищи.
        4. При столкновении игра закрывается с ошибкой Segmentation Fault.
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: "Ожидаемое vs Фактическое поведение"
      description: "Что должно было произойти vs что произошло на самом деле."
      value: |
        **Ожидалось:** Клетка поглощает частицу, шкала энергии увеличивается.
        **Фактически:** Игра аварийно завершается.
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: "Логи / Сообщения об ошибке"
      description: "Скопируйте текст ошибки из консоли или лог-файла. Оберните в тройные кавычки ```."
      render: shell

  - type: input
    id: environment
    attributes:
      label: "Окружение"
      description: "На какой системе обнаружен баг?"
      placeholder: "Windows 11 / Python 3.10.6 / Commit hash: a1b2c3d"

  - type: markdown
    attributes:
      value: |
        **Серьезность (проставьте лейбл после создания issue):**
        - `priority: critical` - игра не запускается/падает
        - `priority: high` - сломана ключевая механика
        - `priority: medium` - баг мешает, но игра продолжается
        - `priority: low` - косметическая проблема
