name: "🎨 Задача для дизайнера"
description: |
  Используйте этот шаблон для постановки задач команде дизайнеров.
  Отвечает: Тимлид / Продакт.
title: "[DESIGN] "
labels: ["type: design", "status: backlog"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: |
        ## 🎨 Дизайн-бриф
        *Заполняется тимлидом или продактом. Четко опишите, что должно быть создано.*

  - type: input
    id: related_feature
    attributes:
      label: "Связанная игровая механика / Фича"
      description: "К какой функции игры относится этот дизайн?"
      placeholder: "Например: Интерфейс древа эволюции, связан с DEV #15"
    validations:
      required: true

  - type: dropdown
    id: design_type
    attributes:
      label: "Тип дизайн-работы"
      description: "Что конкретно нужно создать?"
      multiple: true
      options:
        - UI/UX макет (экран, панель, меню)
        - Графические ассеты (спрайты, иконки)
        - Анимации (спрайт-листы, FX)
        - Иллюстрация / Концепт-арт
        - Визуализация данных (графики, схемы)
    validations:
      required: true

  - type: textarea
    id: design_brief
    attributes:
      label: "Дизайн-бриф и требования"
      description: "Опишите цель, настроение, ограничения. Приложите референсы или скетчи ссылкой."
      placeholder: |
        **Цель:** ...
        **Референсы:** (ссылки на примеры или загруженные скетчи)
        **Тех.требования:** (размеры в px, основной цвет, стиль)
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: "Требуемые результаты (Deliverables)"
      description: "Что именно дизайнер должен предоставить по завершении?"
      value: |
        - [ ] Макеты в Figma (с комментариями для разработчиков).
        - [ ] Исходные файлы (`.fig`, `.psd`, `.ai`).
        - [ ] Экспортированные ассеты в папку `/assets/...` в корректных форматах.
        - [ ] Документ со спецификацией (цвета, шрифты, отступы).
    validations:
      required: true

  - type: input
    id: priority_deadline
    attributes:
      label: "Приоритет и дедлайн"
      placeholder: "Например: Высокий, до 25.12.2023"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **✅ После создания задачи:** Назначьте ответственных (assignees) из команды дизайнеров.
