name: "👨‍💻 Задача для разработчика"
description: | 
  Используйте этот шаблон для постановки технических задач команде разработки.
  Отвечает: Техлид / Архитектор.
title: "[DEV] "
labels: ["type: development", "status: backlog"]
assignees: []  # ИСПРАВЛЕНО: пустой массив вместо пустой строки
body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Техническое задание
        *Заполняется тимлидом или старшим разработчиком. Будьте максимально конкретны.*

  - type: input
    id: parent_epic
    attributes:
      label: "Родительский Epic / Фича"
      description: "Ссылка на общую задачу или описание фичи."
      placeholder: "Например: Epic #42 'Система эволюции'"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "Компонент системы"
      description: "Какой модуль игры затрагивает задача?"
      options:
        - Ядро (Core) - physics, cell, world
        - Эволюция (Evolution) - upgrades, genetics
        - Графика и UI (Graphics) - rendering, interface
        - ИИ и среда (AI/Environment) - npc, world gen
        - Инфраструктура (Infra) - tools, CI/CD, docs
    validations:
      required: true

  - type: textarea
    id: technical_description
    attributes:
      label: "Техническое описание"
      description: "Что нужно реализовать? Опишите алгоритм, классы, методы. Можно псевдокодом."
      placeholder: |
        1. Цель: ...
        2. Способ решения: ...
        3. Пример сигнатуры нового метода:
           `def calculate_mutation(parent_genes):`
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Критерии приемки (Definition of Done)"
      description: "Четкий список условий, при которых задача считается выполненной."
      value: |
        - [ ] Код написан, соответствует PEP8 (проверено black/flake8).
        - [ ] Покрытие unit-тестами >80% для новых функций.
        - [ ] Типизация проверена (mypy).
        - [ ] Логика протестирована вручную в игре.
        - [ ] Code Review пройдено минимум одним участником команды.
        - [ ] Документация в коде (docstrings) обновлена.
        - [ ] Изменения успешно влиты в ветку `develop`.
    validations:
      required: true

  - type: input
    id: estimated_points
    attributes:
      label: "Оценка сложности (Story Points)"
      placeholder: "1, 2, 3, 5, 8, 13"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **✅ После создания задачи:** Назначьте ответственных (assignees) из команды разработки и установите лейбл `status: ready`.
