name: "✨ Предложить новую фичу (Feature Proposal)"
description: |
  Используйте этот шаблон для предложения новой функциональности, механики или улучшения игры.
  **Может заполнять любой член команды.**
title: "[FEATURE] "
labels: ["type: enhancement", "status: backlog"]
assignees: []  # ИСПРАВЛЕНО: пустой массив вместо пустой строки
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Идея новой функциональности

  - type: input
    id: feature_name
    attributes:
      label: "Название фичи"
      placeholder: "Например: Система симбиоза клеток"
    validations:
      required: true

  - type: textarea
    id: problem_motivation
    attributes:
      label: "Проблема / Мотивация"
      description: "Какую игровую или пользовательскую проблему решает эта фича? Почему это важно?"
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: "Предлагаемое решение"
      description: "Опишите, как эта фича должна работать. Можно тезисами."
      placeholder: |
        - Игрок может объединять две клетки в симбиоз через меню...
        - Симбиоз дает бонус к скорости метаболизма, но увеличивает размер...
        - Визуально клетки соединяются мостиком...

  - type: checkboxes
    id: affected_components
    attributes:
      label: "Затронутые компоненты игры"
      description: "Какие части кода и дизайна потребуют изменений?"
      options:
        - label: Ядро игры (Core)
        - label: Система эволюции (Evolution)
        - label: Графика и рендеринг (Graphics)
        - label: Пользовательский интерфейс (UI)
        - label: ИИ (AI)
        - label: Дизайн ассетов (Design Assets)

  - type: textarea
    id: additional_context
    attributes:
      label: "Дополнительный контекст"
      description: "Ссылки на референсы из других игр, скетчи, примеры, любые другие мысли."
