name: "📋 Задача менеджера / тимлида"
description: |
  Используйте этот шаблон для постановки организационных, координационных и управленческих задач.
  Отвечает: Тимлид, Продакт-менеджер, Скрам-мастер.
title: "[MANAGER] "
labels: ["type: management", "status: backlog"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 Организационная задача
        *Заполняется тимлидом или менеджером. Фокусируется на процессе, координации или планировании.*

  - type: input
    id: sprint_milestone
    attributes:
      label: "Спринт / Этап / Веха"
      description: "К какому периоду или цели относится задача?"
      placeholder: "Например: Спринт #1, Подготовка к альфа-тесту, Квартал Q1"
    validations:
      required: true

  - type: dropdown
    id: task_category
    attributes:
      label: "Категория задачи"
      description: "Какой тип организационной работы требуется?"
      options:
        - Планирование и оценка (Planning)
        - Координация команды (Coordination)
        - Анализ и отчётность (Analytics)
        - Процессы и улучшения (Process Improvement)
        - Коммуникации (Communications)
        - Риск-менеджмент (Risk Management)
    validations:
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: "Описание задачи и контекст"
      description: "Что нужно сделать и почему это важно? Опишите организационную проблему или цель."
      placeholder: |
        **Цель:** ...
        **Контекст/Проблема:** ...
        **Ожидаемый организационный результат:** ...
    validations:
      required: true

  - type: textarea
    id: deliverables_outcomes
    attributes:
      label: "Ожидаемые результаты / Деливераблы"
      description: "Что конкретно должно быть создано или достигнуто в результате?"
      value: |
        - [ ] Проведена встреча с протоколом решений
        - [ ] Создан/обновлён документ (roadmap, отчет, ретроспектива)
        - [ ] Координированы действия между N командами/людьми
        - [ ] Принято решение по вопросу...
        - [ ] Риск идентифицирован и план действий составлен
    validations:
      required: true

  - type: input
    id: participants
    attributes:
      label: "Участники / Заинтересованные стороны"
      description: "Кто должен быть вовлечён? (команды, конкретные люди)"
      placeholder: "Например: вся команда (11 девелоперов + 4 дизайнера), техлид, продакт"

  - type: textarea
    id: success_metrics
    attributes:
      label: "Метрики успеха / Критерии завершения"
      description: "Как мы поймём, что задача выполнена успешно?"
      placeholder: |
        - Запланированные встречи проведены, решения задокументированы.
        - Все участники проинформированы о результатах.
        - Необходимые организационные изменения внедрены.
        - Команда понимает следующие шаги.

  - type: input
    id: deadline
    attributes:
      label: "Дедлайн"
      description: "Крайний срок выполнения"
      placeholder: "ДД.ММ.ГГГГ"

  - type: markdown
    attributes:
      value: |
        **✅ После создания задачи:**
        1.  Назначьте ответственного (обычно это тимлид или менеджер).
        2.  Добавьте лейблы `component: infrastructure` и соответствующий `priority:`.
        3.  Измените статус на `status: ready`, когда задача готова к выполнению.
